name: build
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - run: apt update
      - name: install aux deps
        run: apt -y --no-install-recommends install git ca-certificates curl gnupg sudo
      - name: add pgdg pkg repo
        run: >
          echo "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" >> /etc/apt/sources.list.d/pgdg.list &&
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg
      - name: add yeti pkg repo
        run: >
          echo "deb [arch=amd64] http://pkg.yeti-switch.org/debian/bookworm 1.13 main" > /etc/apt/sources.list.d/yeti.list &&
          curl https://pkg.yeti-switch.org/key.gpg | gpg --dearmor > /etc/apt/trusted.gpg.d/pkg.yeti-switch.org.gpg
      - run: apt update
      - name: clone repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install build-deps
        run: apt update && apt -y --no-install-recommends build-dep .
      - name: Setup upterm session
        uses: lhotari/action-upterm@master
        with:
          limit-access-to-actor: true
          limit-access-to-users: furmur
          wait-timeout-minutes: 10
